/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/locations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List locations */
        get: operations["listLocations"];
        put?: never;
        /** Create a location (admin) */
        post: operations["createLocation"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a location */
        get: operations["getLocation"];
        /**
         * Update a location (admin)
         * @description Updates mutable fields (name only). Coordinates, country_code, and timezone are immutable after creation (domain architecture §2.3).
         */
        put: operations["updateLocation"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/locations/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Enable or disable a location (admin)
         * @description Soft status change (BR-LOC-03): disabling stops future collection; historical data remains queryable.
         */
        patch: operations["setLocationStatus"];
        trace?: never;
    };
    "/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List providers */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecasts/latest": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Latest forecast for a provider + location
         * @description Raw forecast data (gated: authenticated user with the read:data API-key scope; AUTH-08).
         */
        get: operations["getLatestForecast"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/collections/trigger": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Trigger an immediate collection (admin) */
        post: operations["triggerCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/collections/{id}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replay a stored collection payload through the current adapter (admin) */
        post: operations["replayCollection"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-collections": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List forecast collections (admin) */
        get: operations["listCollections"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-collections/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a forecast collection (admin) */
        get: operations["getCollection"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Provider rankings (S-01)
         * @description Composite provider rankings for a location + horizon with per-component breakdown, CIs, statuses, ties, and the latest observation context. Public; cached (ETag + LRU 60s).
         */
        get: operations["getRankings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/rankings/methodology": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranking methodology (S-06)
         * @description Published statistical methodology: formulas, default weights, thresholds, coverage penalty, statuses, tie rule, and change history. Static config; long-cached.
         */
        get: operations["getRankingsMethodology"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accuracy/summary": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accuracy summary (S-02 location / S-03 provider)
         * @description Location mode (location_id): providers' metric grid + ranking status + collection window. Provider mode (provider_id): all ranking cells. Exactly one of location_id or provider_id required. Public; cached.
         */
        get: operations["getAccuracySummary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/accuracy": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Accuracy trends (S-04)
         * @description Time-bucketed metric series for a location + horizon + variable + metric_type over a bounded period (<=365 days), bucketed to the requested timezone's local day/week/month boundaries (tz-aware date_trunc, post-scan). Every bucket carries sample_count (hollow points). Public; cached.
         */
        get: operations["getAccuracyTrends"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/providers/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get a provider
         * @description One provider with attribution + lineage (adapter_version, collecting_since) for the S-03 header (§4.1).
         */
        get: operations["getProvider"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-comparison": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Forecast vs. Actual (S-05)
         * @description Bounded public payload for one location + day + variable: per-provider forecast lines at the DR-02-selected issuance, the day's observations (gaps absent), and in-memory day metrics. Public; cached (ETag).
         */
        get: operations["getForecastComparison"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Collection health (S-10, admin)
         * @description Operational triage: per provider×location cell (last success, next scheduled, freshness), provider circuits, observation collector, and system section (payload volume, engine lag, backup/restore status). Served from application tables + statfs + backup status file. Admin only; no-store.
         */
        get: operations["getAdminHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/providers/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Enable or disable a provider (S-11, admin) */
        patch: operations["setProviderStatus"];
        trace?: never;
    };
    "/admin/provider-configurations/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Update a provider configuration (S-11, admin)
         * @description Operator-mutable fields only; the credential reference is never accepted or returned.
         */
        patch: operations["updateProviderConfiguration"];
        trace?: never;
    };
    "/admin/audit-events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Audit events (S-14, admin)
         * @description Keyset-paginated audit trail (newest first), filterable by action, resource_type, user_id. Admin only.
         */
        get: operations["getAuditEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/recompute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Recompute analysis (S-13, admin)
         * @description Runs the analysis pipeline on demand (match → aggregate → rank). Audited.
         */
        post: operations["adminRecompute"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Current user profile (S-09)
         * @description Returns the authenticated user's profile. Self-scope; no-store.
         */
        get: operations["getMe"];
        put?: never;
        post?: never;
        /**
         * Delete own account (S-09; AUTH-09)
         * @description Self-service account deletion. Local rows removed (keys cascade; audit anonymized), then the auth-provider delete propagates.
         */
        delete: operations["deleteMe"];
        options?: never;
        head?: never;
        /**
         * Update current user profile (S-09)
         * @description Updates the authenticated user's mutable fields (default location, preferences). Self-scope; audited; no-store.
         */
        patch: operations["updateMe"];
        trace?: never;
    };
    "/api-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List personal API keys (S-09)
         * @description Lists the authenticated user's API keys (metadata only; never the secret). Self-scope; no-store.
         */
        get: operations["listApiKeys"];
        put?: never;
        /**
         * Create a personal API key (S-09)
         * @description Mints an API key. The plaintext key is returned exactly once (never re-derivable). Audited; no-store.
         */
        post: operations["createApiKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-keys/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke a personal API key (S-09)
         * @description Revokes a key the authenticated user owns (idempotent). Unknown or non-owned keys return 404 (no existence disclosure). Audited.
         */
        delete: operations["revokeApiKey"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List users (S-14, admin)
         * @description Keyset-paginated user list (newest first). Admin only; no-store.
         */
        get: operations["listUsers"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Disable/enable a user (S-14, admin)
         * @description Sets a user's status (active|disabled). Refuses self-target (409 self-lockout). Bans/unbans in the auth provider first, then persists + audits. Admin only.
         */
        patch: operations["setUserStatus"];
        trace?: never;
    };
    "/admin/users/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Delete a user (S-14, admin; AUTH-09)
         * @description Deletes a user account. Refuses self-target (409 self-lockout). Local rows removed (keys cascade; audit anonymized), then the auth-provider delete propagates. Admin only.
         */
        delete: operations["deleteUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/webhook": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Supabase auth webhook receiver (signed)
         * @description Ingests signed Supabase auth events into the audit trail (audit-requirements §5). Public route, gated by an HMAC-SHA256 signature over the raw body in the X-Webhook-Signature header (timing-safe). Non-blocking: a valid signature yields 204 even if the audit write fails; an invalid/missing signature is 401. Mounted only when a webhook secret is configured.
         */
        post: operations["authWebhook"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/me/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request own GDPR export (S-09; AUTH-09)
         * @description Creates an account-data export (user row + API-key metadata + own audit events). One active job per user (409). Self; no-store.
         */
        post: operations["requestMyExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/users/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a user's GDPR export (S-14, admin; AUTH-09)
         * @description Admin-triggered account-data export for a target user. One active job per user (409). Admin only; no-store.
         */
        post: operations["requestUserExport"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/exports/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Download a GDPR export (AUTH-09)
         * @description Streams the account-data JSON for a completed, unexpired export the caller may access (requester, target, or admin). Self/admin; no-store; 404 unknown/non-owned, 410 when the 24h window closed.
         */
        get: operations["downloadExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/forecast-collections/{id}/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Snapshots of a forecast collection (admin)
         * @description Returns the collection's lineage row plus all its stored snapshots — the historical raw-data view behind /forecasts/latest.
         */
        get: operations["getCollectionSnapshots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/provider-configurations": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List provider configurations (S-11, admin)
         * @description All configurations (active + disabled) with has_credential and the collection schedule. The credential reference is never echoed (BR-08).
         */
        get: operations["listProviderConfigurations"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        Envelope: {
            data: unknown;
            metadata?: components["schemas"]["Metadata"];
            freshness?: components["schemas"]["Freshness"];
            attribution?: components["schemas"]["Attribution"][];
            warnings?: components["schemas"]["Warning"][];
            pagination?: components["schemas"]["Pagination"];
            partial_result?: boolean;
            provenance?: components["schemas"]["Provenance"];
        };
        Metadata: {
            request_id?: string;
            /** Format: date-time */
            generated_at?: string;
            timezone?: string;
            units?: {
                [key: string]: string;
            };
            methodology_version?: string;
            weights_version?: string;
        };
        Freshness: {
            /** @enum {string} */
            state?: "fresh" | "delayed" | "stale" | "unavailable";
            /** Format: date-time */
            last_updated?: string;
            age_seconds?: number;
            threshold_seconds?: number;
            reason?: string;
        };
        Attribution: {
            provider?: string;
            text?: string;
            url?: string;
        };
        Warning: {
            provider_id?: string;
            /** @enum {string} */
            code?: "provider_unavailable" | "stale";
            message?: string;
            since?: string;
        };
        Pagination: {
            next_cursor?: string;
            has_more?: boolean;
        };
        Problem: {
            type: string;
            title: string;
            status: number;
            detail?: string;
            instance?: string;
            request_id: string;
            retryable?: boolean;
            errors?: {
                field?: string;
                message?: string;
            }[];
        };
        CreateLocationRequest: {
            name: string;
            latitude: number;
            longitude: number;
            country_code: string;
            timezone: string;
            /** @default false */
            allow_near_duplicate: boolean;
            /** @description Operator justification for accepting a near-duplicate (BR-LOC-01 override; audited). Required when allow_near_duplicate is true. */
            override_reason?: string;
        };
        UpdateLocationRequest: {
            name: string;
        };
        SetLocationStatusRequest: {
            /**
             * @description Target status. Only active and disabled are settable; archived is reserved.
             * @enum {string}
             */
            status: "active" | "disabled";
        };
        TriggerCollectionRequest: {
            /** Format: uuid */
            provider_id: string;
            /** Format: uuid */
            location_id: string;
        };
        Provenance: {
            observation_provenance_mix?: {
                [key: string]: number;
            };
            observation_sources?: string[];
            quality_weighting_applied?: boolean;
        };
    };
    responses: {
        /** @description RFC 7807 problem */
        Problem: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listLocations: {
        parameters: {
            query?: {
                active?: boolean;
                cursor?: string;
                limit?: number;
                /** @description reserved (MVP ignores; spatial filtering is post-MVP) */
                bbox?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Locations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    createLocation: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateLocationRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Location */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    updateLocation: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateLocationRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    setLocationStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetLocationStatusRequest"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Providers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getLatestForecast: {
        parameters: {
            query: {
                location_id: string;
                provider_id: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Latest forecast */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    triggerCollection: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerCollectionRequest"];
            };
        };
        responses: {
            /** @description Collection result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
            429: components["responses"]["Problem"];
        };
    };
    replayCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay collection result */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listCollections: {
        parameters: {
            query?: {
                provider_id?: string;
                location_id?: string;
                status?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collections */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    getCollection: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getRankings: {
        parameters: {
            query: {
                location_id: string;
                horizon_minutes?: number;
                horizon_profile?: "uniform" | "short_term" | "daily_planning";
                min_sample_count?: number;
                period_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Rankings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getRankingsMethodology: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Methodology */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
    getAccuracySummary: {
        parameters: {
            query?: {
                location_id?: string;
                provider_id?: string;
                horizon_minutes?: number;
                period_days?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accuracy summary */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getAccuracyTrends: {
        parameters: {
            query: {
                location_id: string;
                variable: string;
                metric_type: string;
                provider_id?: string;
                horizon_minutes?: number;
                aggregation?: "daily" | "weekly" | "monthly";
                period_start?: string;
                period_end?: string;
                tz?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Accuracy trends */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            422: components["responses"]["Problem"];
        };
    };
    getProvider: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Provider */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    getForecastComparison: {
        parameters: {
            query: {
                location_id: string;
                /** @description ISO date interpreted in the location timezone */
                date: string;
                variable: "temperature" | "wind_speed" | "humidity" | "pressure" | "precipitation";
                horizon_minutes: number;
                /** @description CSV of provider UUIDs (default: all active) */
                providers?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Forecast comparison */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getAdminHealth: {
        parameters: {
            query?: {
                provider_id?: string;
                location_id?: string;
                status?: "fresh" | "delayed" | "stale" | "unavailable";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection health */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    setProviderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    updateProviderConfiguration: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    getAuditEvents: {
        parameters: {
            query?: {
                action?: string;
                resource_type?: string;
                user_id?: string;
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    adminRecompute: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    deleteMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    updateMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** Format: uuid */
                    default_location_id?: string;
                    preferences?: Record<string, never>;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    listApiKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
        };
    };
    createApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    name: string;
                    scopes?: string[];
                    rate_limit_per_min?: number;
                    /** Format: date-time */
                    expires_at?: string;
                };
            };
        };
        responses: {
            /** @description Created (plaintext key returned once) */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    revokeApiKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Revoked */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
        };
    };
    listUsers: {
        parameters: {
            query?: {
                cursor?: string;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
        };
    };
    setUserStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @enum {string} */
                    status: "active" | "disabled";
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
            422: components["responses"]["Problem"];
        };
    };
    deleteUser: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    authWebhook: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    type?: string;
                    subject?: string;
                };
            };
        };
        responses: {
            /** @description Accepted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Problem"];
        };
    };
    requestMyExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    requestUserExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            401: components["responses"]["Problem"];
            403: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            409: components["responses"]["Problem"];
        };
    };
    downloadExport: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Account-data export (attachment) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": Record<string, never>;
                };
            };
            401: components["responses"]["Problem"];
            404: components["responses"]["Problem"];
            410: components["responses"]["Problem"];
        };
    };
    getCollectionSnapshots: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Collection with snapshots */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
            404: components["responses"]["Problem"];
        };
    };
    listProviderConfigurations: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Configurations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Envelope"];
                };
            };
        };
    };
}
