// Package openapi embeds the committed OpenAPI 3.1 specification so the
// binary can serve it at /api/v1/openapi.json. The spec is generated from
// code annotations via `make docs` (swag) and CI-checked for drift.
package openapi

import _ "embed"

// Spec is the committed OpenAPI document (regenerated by `make docs`).
//
//go:embed openapi.json
var Spec []byte
